// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelAlert():Promise<void>;

export function GetMapList():Promise<Array<string>>;

export function SetAlert(arg1:Array<string>,arg2:number):Promise<void>;
