// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelAlert() {
  return window['go']['main']['App']['CancelAlert']();
}

export function GetFilterLists() {
  return window['go']['main']['App']['GetFilterLists']();
}

export function SetAlert(arg1) {
  return window['go']['main']['App']['SetAlert'](arg1);
}
