// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelAlert():Promise<void>;

export function GetFilterLists():Promise<main.FilterLists>;

export function SetAlert(arg1:main.AlertConfig):Promise<void>;
