name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
    contents: write
    packages: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Wails App
        uses: dAppServer/wails-build-action@main
        with:
          build-name: "BattleBit_Notifier"
          build-platform: "windows/amd64"
          package: true

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/bin/BattleBit_Notifier.exe"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false